apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: i3gis-appsec
spec:
  steps:
    - name: appsec-scan
      image: registry.lab.i-3.my.id:5000/curl/curl:8
      script: |
        #!/bin/sh
        echo "Scanning project secret-check with i3gis..."
        scanResponse=$(curl --write-out '%{http_code}' --request POST -sL --url 'https://api.i3gis.id/scan-svc/scan' --header 'Content-Type: application/json' --header 'Authorization: Bearer Q9uIuSdygdW+T1mIVDjVG8Ul6tkk8tp2g3DT2F1X8efGCf8eXOD2Yjj+/Aw5BnIpJqIwM0DfeBAaM9iWUqVJubqFAXtxxXsaHBdeAdSU8y6y6BlSOW5qf2tfAkxKVn7f' --data '{"project_id":63}')
        scanCode=$(echo $scanResponse | grep -o ...$)
        echo "HTTP response status code: $scanCode"
        if [ $scanCode = "200" ]; then
          echo "Scan project secret-check with i3gis..."
        else
          echo "Response: $scanResponse"
          echo "Build failed because scan was not successful..."
          exit 1
        fi
        echo "Scan project secret-check with i3gis is starting..."

    - name: appsec-scan-status
      image: registry.lab.i-3.my.id:5000/curl/curl:8
      script: |
        #!/bin/sh
        echo "Get scan status..."
        status_running=true
        while [ "$status_running" = true ]; do
          sleep 5
          echo "Scan still running..."
          checkResponse=$(curl --write-out ''%{http_code}'' --request GET -sL --url 'https://api.i3gis.id/scan-svc/scan/63' --header 'Content-Type: application/json' --header 'Authorization: Bearer Q9uIuSdygdW+T1mIVDjVG8Ul6tkk8tp2g3DT2F1X8efGCf8eXOD2Yjj+/Aw5BnIpJqIwM0DfeBAaM9iWUqVJubqFAXtxxXsaHBdeAdSU8y6y6BlSOW5qf2tfAkxKVn7f')
          checkCode=$(echo $checkResponse | grep -o ...$)
          echo "HTTP response status code: $checkCode"
          if [ $checkCode != "200" ] && [ $checkCode != "404" ]; then
            echo "Response: $checkResponse"
            echo "Scan failed..."
            exit 1
          fi
          if [ $checkCode = "404" ]; then
            echo "Scan finished..."
            status_running=false
          fi
        done
