apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: i3gisintegration
spec:
  steps:
    - name: scan
      image: alpine
      script: |
        #!/bin/sh
        urlScan="https://api.i3gis.id/scan-svc/scan"
        token="Bearer 6Kb03xxdXX88x6MQRj3QwZv9yQsOg/RM0xfJABSZsU+qfRLjQyJDTQTBrvWbke0lv9xwfxD1Mc3q9tGIkh8fOfTilhxB5TLowFmR3MEoxiO1hN0cCdMA5hZwHIoaRVnKoIWVrqgsOOJym5bEFnBPww=="
        project_id=5

        responseScan=$(curl -s -w '\n%{response_code}' --location -g --request POST $urlScan \
                        --header 'Content-Type: application/json' \
                        --header "Authorization: $token" \
                        -d "{\"project_id\":$project_id}")

        codeScan=$(echo "$responseScan" | tail -n1)

        echo "HTTP response status code: $codeScan"

        if [ "$codeScan" != "200" ]; then
            echo "Response: $responseScan"
            exit 1
        else
            echo "Scan project $project_id with i3gis..."
        fi

        echo "Scan project $project_id with i3gis is starting..."
