apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: i3gis-task
spec:
  steps:
    - name: consec-env
      image: debian
      script: |
        echo "I3GIS_SCAN_IMAGE_TAG=1.0.0" > $(results.dir)/i3gis_output

    - name: consec-scan
      image: debian
      script: |
        apt-get update && apt-get install -y curl
        scanResponse=$(curl --write-out '%{http_code}' --request POST -sL --url '/api/v1/integration/image/scan' --header 'Content-Type: application/json' --header 'Authorization: Bearer YOUR_AUTH_TOKEN_HERE' --data '{"container_project_id":2,"image_name":"nginx","image_tag":"1.0.0"}')
        scanCode=$(echo $scanResponse | grep -o ...$)
        echo "HTTP response status code: $scanCode"
        if [ "$scanCode" = "201" ]; then
          echo "Scan successful..."
          echo "$scanResponse" > $(results.dir)/scan_output
        else
          echo "Response: $scanResponse"
          echo "Scan failed..."
          exit 1
        fi

    - name: consec-scan-status
      image: debian
      script: |
        apt-get update && apt-get install -y curl
        echo "Get scan status..."
        status_running=true
        while [ "$status_running" = true ]; do
          sleep 5
          echo "Scan still running..."
          # Add your logic to check scan status
          # ...
        done
